EDITOR=nvim
VISUAL=nvim
TERMINAL=ghostty
BROWSER=zen-browser
XDG_CURRENT_DESKTOP=niri
XDG_SESSION_TYPE=wayland
QT_QPA_PLATFORMTHEME=qt6ct
MOZ_ENABLE_WAYLAND=1
SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/keyring/ssh
XCURSOR_THEME=catppuccin-mocha-dark-cursors
XCURSOR_SIZE=24
