[search]
placeholder = "Search..."
delay = 0
force_keyboard_focus = true

[ui]
fullscreen = false
anchors = { top = true, bottom = false, left = false, right = false }

[ui.window]
width = 600
height = 400

[builtins.applications]
enabled = true
prioritize_new = true

[builtins.commands]
enabled = true

[builtins.files]
enabled = true

[builtins.dmenu]
enabled = true

[terminal_emulator]
program = "ghostty"
flag = "-e"

[theme]
name = "catppuccin"
